### ISSUE TITLE
Error with the mapscript module : AttributeError: 'module' object has no attribute 'MS_TRUE'

### ISSUE THREAD

**Issue by Namrod21** [faunalia/rt_mapserver_exporter#9] opened 2015-12-12 20:56 UTC
Hi !

I installed the RT MapServer Exporter on QGIS 2.6.1 (Mac OS X 10.9 Mavericks), and it doesn't work. Each time I get the same error:

```
Traceback (most recent call last):
  File "/Users/leonard/.qgis2/python/plugins/rt_mapserver_exporter/plugin.py", line 65, in run
    from .mapfileexportdlg import MapfileExportDlg
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/leonard/.qgis2/python/plugins/rt_mapserver_exporter/mapfileexportdlg.py", line 31, in 
    import MapfileExporter
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/leonard/.qgis2/python/plugins/rt_mapserver_exporter/MapfileExporter.py", line 9, in 
    from utils import *
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/leonard/.qgis2/python/plugins/rt_mapserver_exporter/utils.py", line 1, in 
    import mapscript
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/mapscript.py", line 99, in 
    MS_TRUE = _mapscript.MS_TRUE
AttributeError: 'module' object has no attribute 'MS_TRUE'
```

I have MapServer 7.0.0 installed from source and Python 2.7.5, which is the default version on my Mac. `python import mapscript` works.

**Comment by luipir** [comment] 2015-12-12 21:22
I should that i never tested under osx, but now i can finding time to prepare it, but for sure i can't install 2.6 but at least ltr from boundless packaged qgis for osx.

The problem seems with the packaged mapscript version... Can you say mi what is the installed version?

Can you check with a more fresh packaged version?

**Comment by Namrod21** [comment] 2015-12-12 21:29
Thanks for your answer ! At the top of the file `mapscript.py` I found Version 3.0.7 (this is the default version installed by MapServer). Unfortunately I don't manage to install a newer version:

```
> pip install mapscript

Collecting mapscript
/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached mapscript-5.6.3.0.zip
Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.6c9 in /usr/local/lib/python2.7/site-packages (from mapscript)
Building wheels for collected packages: mapscript
  Running setup.py bdist_wheel for mapscript
  Complete output from command /usr/local/bin/python -c "import setuptools;__file__='/private/var/folders/kv/1t6_h_t53x776lwwg3c5nyzh0000gn/T/pip-build-UmnEo_/mapscript/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/kv/1t6_h_t53x776lwwg3c5nyzh0000gn/T/tmpJaigSZpip-wheel-:
  sh: mapserver-config: command not found
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-intel-2.7
  copying mapscript.py -> build/lib.macosx-10.9-intel-2.7
  running egg_info
  writing requirements to mapscript.egg-info/requires.txt
  writing mapscript.egg-info/PKG-INFO
  writing top-level names to mapscript.egg-info/top_level.txt
  writing dependency_links to mapscript.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'mapscript.egg-info/SOURCES.txt'
  writing manifest file 'mapscript.egg-info/SOURCES.txt'
  running build_ext
  building '_mapscript' extension
  creating build/temp.macosx-10.9-intel-2.7
  creating build/temp.macosx-10.9-intel-2.7/pygdioctx
  cc -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -arch x86_64 -arch i386 -pipe -I/usr/include/python2.7 -c mapscript_wrap.c -o build/temp.macosx-10.9-intel-2.7/mapscript_wrap.o
  mapscript_wrap.c:2040:11: warning: explicitly assigning a variable of type 'int' to itself [-Wself-assign]
                      res = SWIG_AddCast(res);
                      ~~~ ^              ~~~
  mapscript_wrap.c:2043:11: warning: explicitly assigning a variable of type 'int' to itself [-Wself-assign]
                      res = SWIG_AddCast(res);
                      ~~~ ^              ~~~
  mapscript_wrap.c:2564:10: fatal error: 'mapserver.h' file not found
  #include "mapserver.h"
           ^
  2 warnings and 1 error generated.
  error: command 'cc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for mapscript
Failed to build mapscript
Installing collected packages: mapscript
  Running setup.py install for mapscript
    Complete output from command /usr/local/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/kv/1t6_h_t53x776lwwg3c5nyzh0000gn/T/pip-build-UmnEo_/mapscript/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/kv/1t6_h_t53x776lwwg3c5nyzh0000gn/T/pip-9fOA5t-record/install-record.txt --single-version-externally-managed --compile:
    sh: mapserver-config: command not found
    running install
    running build
    running build_py
    running egg_info
    writing requirements to mapscript.egg-info/requires.txt
    writing mapscript.egg-info/PKG-INFO
    writing top-level names to mapscript.egg-info/top_level.txt
    writing dependency_links to mapscript.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'mapscript.egg-info/SOURCES.txt'
    writing manifest file 'mapscript.egg-info/SOURCES.txt'
    running build_ext
    building '_mapscript' extension
    cc -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -arch x86_64 -arch i386 -pipe -I/usr/include/python2.7 -c mapscript_wrap.c -o build/temp.macosx-10.9-intel-2.7/mapscript_wrap.o
    mapscript_wrap.c:2040:11: warning: explicitly assigning a variable of type 'int' to itself [-Wself-assign]
                        res = SWIG_AddCast(res);
                        ~~~ ^              ~~~
    mapscript_wrap.c:2043:11: warning: explicitly assigning a variable of type 'int' to itself [-Wself-assign]
                        res = SWIG_AddCast(res);
                        ~~~ ^              ~~~
    mapscript_wrap.c:2564:10: fatal error: 'mapserver.h' file not found
    #include "mapserver.h"
             ^
    2 warnings and 1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/kv/1t6_h_t53x776lwwg3c5nyzh0000gn/T/pip-build-UmnEo_/mapscript/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/kv/1t6_h_t53x776lwwg3c5nyzh0000gn/T/pip-9fOA5t-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/kv/1t6_h_t53x776lwwg3c5nyzh0000gn/T/pip-build-UmnEo_/mapscript
```

**Comment by luipir** [comment] 2015-12-12 22:31
in the latter case seems you have to install also mapserver dev packages to allow a python-mapscript setup.

**Comment by Namrod21** [comment] 2015-12-12 22:49
Thanks, but where can I find these packages ?

**Comment by luipir** [comment] 2015-12-13 10:27
How did you installed mapserver?

**Comment by Namrod21** [comment] 2015-12-13 10:33
I installed mapserver by compiling the source code. I downloaded the file `mapserver-rel-7-0-0.tar.gz` from here : http://mapserver.org/download.html

**Comment by Namrod21** [comment] 2015-12-13 13:21
I tried something else : I installed Mapserver 6.2.2 with Homebrew. I can import the mapscript module whith python and `mapscript.MS_VERSION` returns `6.2.2`. I copied the `mapscript.py` and `_mapscript.so` files in the extensions directory used by QGIS, but when I try to use the RT MapServer Exporter, I got another error : 

```
Traceback (most recent call last):
  File "/Users/user/.qgis2/python/plugins/rt_mapserver_exporter/plugin.py", line 65, in run
    from .mapfileexportdlg import MapfileExportDlg
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/leonard/.qgis2/python/plugins/rt_mapserver_exporter/mapfileexportdlg.py", line 31, in 
    import MapfileExporter
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/leonard/.qgis2/python/plugins/rt_mapserver_exporter/MapfileExporter.py", line 9, in 
    from utils import *
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/leonard/.qgis2/python/plugins/rt_mapserver_exporter/utils.py", line 1, in 
    import mapscript
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/mapscript.py", line 28, in 
    _mapscript = swig_import_helper()
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/mapscript.py", line 24, in swig_import_helper
    _mod = imp.load_module('_mapscript', fp, pathname, description)
ImportError: dlopen(/Applications/QGIS.app/Contents/MacOS/../Resources/python/_mapscript.so, 2): no suitable image found.  Did find:
    /Applications/QGIS.app/Contents/MacOS/../Resources/python/_mapscript.so: unknown file type, first eight bytes: 0x23 0x20 0x54 0x68 0x69 0x73 0x20 0x66
```

**Comment by luipir** [comment] 2015-12-14 08:29
you are facing installing problem that are not part or plugin problem

the last one seems and uncorrect set of LD_LYBRARY_PATH. e.g the path where to find dynamic lybraries.

first of all I suggest this simple code from the qgis python console:

import mapscript

you should face the same error => the problem is outside the plugin and I woyuld close this tiket.

btw, the problem souldn't related to QGIS too... I just sugest to use QGIS python console to be sure you are running under the same qgis env.

this problme you are facing would be notified in qgis-developer or kingchaos or brewer lists

cheers

**Comment by Namrod21** [comment] 2015-12-14 10:04
Ok, thanks for you help, it finally works ! Actually, QGIS uses the default python script, but seems to use his own paths. Thus, it didn't see the mapscript files located at `/usr/local/lib/python2.7/sites-package/`. It seems that my mistake was to copy these files into a directory where Python could find them (such as `/Library/Python/2.7/sites-package/`) whereas it was not real files but symlinks to the original files located at `/usr/local/Cellar/mapserver/6.2.2/lib/python2.7/sites-package/`. I copied these original files to a correct directory, and now it works fine.

Thanks again for your help !

**Comment by luipir** [comment] 2015-12-14 10:17
may I suggest to file a package issue for mapserver 7 version?
btw I'll close the tiket, feel free to reopen it if you think it is not closed.

regards

**Closed as completed by luipir** 2015-12-14 10:17 UTC
